name: "lib-test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lib-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    env:
      CI_JOB_NUMBER: 1

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run lib:build

      - name: Test library
        run: ng test @fil0157/ngx-themes --watch=false --browsers=ChromeHeadless
